package camel_case;

/**
 * The values in this file are automatically generated by the generateData task. Editing them
 * manually is useless, they are automatically replaced on every build.
 */
public class GeneratedData {
  public static final int MESSAGE_HASH_SECRET_1 = 156;
  public static final int MESSAGE_HASH_SECRET_2 = 171;
  public static final int MESSAGE_HASH_SECRET_3 = -163;
}
